sudo: required
services:
  - docker

before_install:
  - travis_wait docker build -t momo611/docker-practice -f Dockerfile.dev .

script:
  - docker run momo611/docker-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:
  app: //same name as elasticbeanstalk
  env: "Docker-"Docker-env"
  bucket_name: //from s3 bucket
  bucket_path: //bucket-path
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY